@startuml
left to right direction

actor "Advogado" as Advogado
actor "Funcionário" as Funcionario

usecase "Selecionar UFs para monitorar publicações" as UC5

Advogado -- UC5
Funcionario -- UC5

@enduml
