@startuml
left to right direction

actor "Advogado" as Advogado
actor "Funcionário" as Funcionario

usecase "Gerenciar audiências cronologicamente" as UC8

Advogado -- UC8
Funcionario -- UC8

@enduml
