@startuml
left to right direction

actor "Advogado" as Advogado
actor "Funcionário" as Funcionario

usecase "Interagir com notificações das publicações" as UC10

Advogado -- UC10
Funcionario -- UC10

@enduml
